# Generated by Django 4.0.3 on 2022-06-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_on',
            new_name='Booked_on',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='Booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='Doc_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='Patient_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='P_name',
            new_name='Patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='Patient_phone',
        ),
    ]
